### PR TITLE
Grab stream bitrate

### PR DESCRIPTION
**Pull request by tahajahangir**
Currently, sound/video bitrate is not included in probe results. (only total bitrate is included)

### CODE REVIEW

**Comment by Kami** [comment]
Missing a test case, otherwise LGTM

**Comment by tahajahangir** [comment]
In think the best way to test this new feature to change `MediaStreamInfo.__repr__` and also change the `test_ffmpeg_probe` (not extend it). Do you agree?

**Comment by Kami** [comment]
@tahajahangir Yes - you can add extra assertions to `test_ffmpeg_probe`, thanks!

**Comment by senko** [comment]
Looks good to me, yeah please just add the tests.

Regarding testing via `repr()`, it's not guaranteed that its output won't change in the future (the idea is to make it as useful as possible, but the output itsn't stable API). So while testing that repr is useful is good, I'd prefer explicit asserts for bitrate as well (in addition to updating the `repr()` test if needed).

**Comment by tahajahangir** [comment]
Test added (both explicit assert, and repr change)

**Comment by senko** [comment]
Awesome, thanks!

**Pull request merged**
