### PR TITLE
Fixed small error with 2 pass encoding

### PR DESCRIPTION
**Pull request by flamedmg**
Fixed small error with 2 pass encoding

### CODE REVIEW

**Comment by senko** [comment]
Hey Dmitry, thanks for the pull req, and sorry for the late reply.

I don't think it'd be good to have the converter just print out various debugging info. Sure it's useful when debugging, but not so in the normal operation.

Perhaps a good way to do it would be to use python's `logging` module, and do something like:

```
import logging
log = logging.getLogger(__name__)
...
# use log.debug instead of print
log.debug('Running ffmpeg with commands: ' + ' '.join(cmds))
```

This way it's easy to turn it on and off (by using `logging.basicConfig()` or a more elaborate logging scheme), redirect it, add timestamps, etc.

Could I interest you in adding support for this? If not, maybe the first step would be to remove the prints, and we can add the logging output at some other time.

**Comment by flamedmg** [comment]
Hi Senko!
Thank you for contacting me! Yes i will do this. I inserted print to debug
quickly and initially not planned to pull request other changes i made in
the code. I came from .net development and is new to python and django so
please continue to guide me :)

2013/3/18 Senko Rašić notifications@github.com

> Hey Dmitry, thanks for the pull req, and sorry for the late reply.
> 
> I don't think it'd be good to have the converter just print out various
> debugging info. Sure it's useful when debugging, but not so in the normal
> operation.
> 
> Perhaps a good way to do it would be to use python's logging module, and
> do something like:
> 
> import logging
> log = logging.getLogger(**name**)
> ...
> 
> # use log.debug instead of print
> 
> log.debug('Running ffmpeg with commands: ' + ' '.join(cmds))
> 
> This way it's easy to turn it on and off (by using logging.basicConfig()or a more elaborate logging scheme), redirect it, add timestamps, etc.
> 
> Could I interest you in adding support for this? If not, maybe the first
> step would be to remove the prints, and we can add the logging output at
> some other time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/senko/python-video-converter/pull/9#issuecomment-15044925
> .

## 

Thanks & Regards
Dmitry

**Comment by senko** [comment]
Hey Dmitry, no problem, thanks for your contribution :)

**Comment by tahajahangir** [comment]
I think this can be closed in precedence of #22

**Comment by senko** [comment]
Agreed, thanks @tahajahangir and @flamedmg.

**Pull request closed without merging**
