### PR TITLE
Add mp3 format to allow converting to mp3 files

### PR DESCRIPTION
**Pull request by tahajahangir**

### CODE REVIEW

**Comment by Kami** [comment]
Awesome. Change looks good to me, but it's a relatively big one so it would be nice to add some test cases for it.

You can find some sample audio files in different formats which you can use in the tests at:
- http://download.wavetlan.com/SVV/Media/HTTP/http-aac.htm
- https://commons.wikimedia.org/wiki/File:Example.ogg

**Comment by tahajahangir** [comment]
Test case added

**Comment by Kami** [comment]
LGTM, +1

**Comment by senko** [comment]
Agree, this is useful, looks good, thanks @tahajahangir for the patch.

**Pull request merged**
