### PR TITLE
Development

### PR DESCRIPTION
**Pull request by cytec**
added basic subtitle support (mainly -scodec copy command) and also a map option to map the whole stream as of http://ffmpeg.org/ffmpeg.html#Main-options

-map 0 gives us the option to copy all audio/video and subtitle streams with the given settings :)

### CODE REVIEW

**Comment by senko** [comment]
Hey @cytec thanks for the subtitle handling code! I've got a couple of minor comments, otherwise looks great! If you could just address the issues I commented about, I'll be happy to merge.

**Comment by cytec** [comment]
@senko fixed the comments and also added some new codecs and reordered the codecs for better overview. seems like all tests are passing now.

**Comment by cytec** [comment]
@senko any news on this?

**Comment by senko** [comment]
@cytec oops sorry for dropping the ball on this one. Reviewed the new commits, looks great, thanks!

**Comment by cytec** [comment]
@senko Thanks :)

**Pull request merged**
